'***********************************
'TRADUCCIO
'***********************************
Friend Module Traduccions

    'per traduir textos
    Friend vpEN As New Dictionary(Of String, String) 'al anglès
    Friend vpES As New Dictionary(Of String, String) 'al castellà

    Sub CarregaT()
        'omplim les taules de traduccio
        vpEN.Clear()
        vpES.Clear()

        vpEN.Add("' amb Element #", "' with Element #")
        vpEN.Add("Abr", "Apr")
        vpEN.Add("Abril", "April")
        vpEN.Add("Ago", "Aug")
        vpEN.Add("Agost", "August")
        vpEN.Add("al", "to")
        vpEN.Add("CONFIRMACIÓ", "CONFIRM")
        vpEN.Add("dc", "Wed")
        vpEN.Add("de", "from")
        vpEN.Add("del", "from")
        vpEN.Add("Des", "Dec")
        vpEN.Add("Desembre", "December")
        vpEN.Add("dg", "Sun")
        vpEN.Add("Dia", "Day")
        vpEN.Add("dijous", "Thursday")
        vpEN.Add("dilluns", "Monday")
        vpEN.Add("dimarts", "Tuesday")
        vpEN.Add("dimecres", "Wednesday")
        vpEN.Add("dissabte", "Saturday")
        vpEN.Add("diumenge", "Sunday")
        vpEN.Add("divendres", "Friday")
        vpEN.Add("dj", "Thu")
        vpEN.Add("dl", "Mon")
        vpEN.Add("dm", "Tue")
        vpEN.Add("DobleClick per mode dia", "DblClick for day view")
        vpEN.Add("DobleClick per mode mes", "DblClick for month view")
        vpEN.Add("DobleClick per mode recurs", "DblClick for view of resource")
        vpEN.Add("DobleClick per mode setmana", "DblClick for week view")
        vpEN.Add("ds", "Sat")
        vpEN.Add("dv", "Fri")
        vpEN.Add("Eliminar '", "Delete '")
        vpEN.Add("ELIMINAR", "DELETE")
        vpEN.Add("Error al actualitzar '", "Error on update '")
        vpEN.Add("Error al eliminar '", "Error on delete '")
        vpEN.Add("Febrer", "February")
        vpEN.Add("Gen", "Jan")
        vpEN.Add("Gener", "January")
        vpEN.Add("INFORMACIÓ", "INFORMATION")
        vpEN.Add("Juliol", "July")
        vpEN.Add("Juny", "June")
        vpEN.Add("Mai", "May")
        vpEN.Add("Maig", "May")
        vpEN.Add("Març", "March")
        vpEN.Add("Mes", "Month")
        vpEN.Add("No es pot sobrepassar l'horari ", "Exceeding the day bounds ")
        vpEN.Add("no trobat a llista de recursos dia", "not found in resources daily list")
        vpEN.Add("Novembre", "November")
        vpEN.Add("Octubre", "October")
        vpEN.Add("Recurs", "Resource")
        vpEN.Add("recursos a", "resources to")
        vpEN.Add("recursos", "resources")
        vpEN.Add("Set", "Sep")
        vpEN.Add("Setembre", "September")
        vpEN.Add("Setmana", "Week")
        vpEN.Add("Setmana del", "Week from")
        vpEN.Add(": Cal informar la data/hora d'inici de l'element.", ": Element start time is mandatory.'")
        vpEN.Add(": No es pot modificar elements fets.", ": Can't update done elements.")
        vpEN.Add(": Solapament de recurs '", ": Overlap of resource '")

        vpES.Add("' amb Element #", "' con Elemento #")
        vpES.Add("Agost", "Agosto")
        vpES.Add("CONFIRMACIÓ", "CONFIRMACIÓN")
        vpES.Add("dc", "mié")
        vpES.Add("Des", "Dic")
        vpES.Add("Desembre", "Diciembre")
        vpES.Add("dg", "dom")
        vpES.Add("dijous", "jueves")
        vpES.Add("dilluns", "lunes")
        vpES.Add("dimarts", "martes")
        vpES.Add("dimecres", "miércoles")
        vpES.Add("dissabte", "sábado")
        vpES.Add("diumenge", "domingo")
        vpES.Add("divendres", "viernes")
        vpES.Add("dj", "jue")
        vpES.Add("dl", "lun")
        vpES.Add("dm", "mar")
        vpES.Add("DobleClick per mode dia", "DobleClick para modo día")
        vpES.Add("DobleClick per mode mes", "DobleClick para modo mes")
        vpES.Add("DobleClick per mode recurs", "DobleClick para modo recurso")
        vpES.Add("DobleClick per mode setmana", "DobleClick para modo semana")
        vpES.Add("ds", "sáb")
        vpES.Add("dv", "vie")
        vpES.Add("No es pot sobrepassar l'horari ", "Se sobrepasa los límites del día ")
        vpES.Add("Element #", "Elemento #")
        vpES.Add("Eliminar '", "¿ Eliminar '")
        vpES.Add("Error al actualitzar '", "Error al actualizar '")
        vpES.Add("Febrer", "Febrero")
        vpES.Add("Gen", "Ene")
        vpES.Add("Gener", "Enero")
        vpES.Add("INFORMACIÓ", "INFORMACIÓN")
        vpES.Add("Juliol", "Julio")
        vpES.Add("Juny", "Junio")
        vpES.Add("Mai", "May")
        vpES.Add("Maig", "Mayo")
        vpES.Add("Març", "Marzo")
        vpES.Add("no trobat a llista de recursos dia", "no encontrado en lista de recursos dia")
        vpES.Add("Novembre", "Noviembre")
        vpES.Add("Recurs", "Recurso")
        vpES.Add("Set", "Sep")
        vpES.Add("Setembre", "Septiembre")
        vpES.Add("Setmana", "Semana")
        vpES.Add("Setmana del", "Semana del")
        vpES.Add(": Cal informar la data/hora d'inici de l'element.", ": Obligatorio informar fecha/hora de inicio del elemento.'")
        vpES.Add(": No es pot modificar elements fets.", ": No se puede modificar elementos realizados.")
        vpES.Add(": Solapament de recurs '", ": Solapamiento de recurso '")

    End Sub

End Module


